"""initial schema

Revision ID: 92da9ab934c3
Revises: 
Create Date: 2026-09-08 15:51:27.670439

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '92da9ab934c3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_categories_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_groups_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_users_status_valid')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('google_id', name=op.f('uq_users_google_id'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('courses',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', 'ARCHIVED')", name=op.f('ck_courses_status_valid')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_courses_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_courses_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index('ix_courses_owner_id', 'courses', ['owner_id'], unique=False)
    op.create_index('ix_courses_published_at', 'courses', ['published_at'], unique=False)
    op.create_index('ix_courses_status', 'courses', ['status'], unique=False)
    op.create_table('user_groups',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_user_groups_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_groups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_user_groups'))
    )
    op.create_table('course_assignments',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overdue_action', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("overdue_action IN ('ALLOW_CONTINUE', 'BLOCK')", name=op.f('ck_course_assignments_overdue_action_valid')),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_course_assignments_status_valid')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_assignments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_course_assignments_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_assignments'))
    )
    op.create_index(op.f('ix_course_assignments_course_id'), 'course_assignments', ['course_id'], unique=False)
    op.create_table('course_categories',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_course_categories_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_categories_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'category_id', name=op.f('pk_course_categories'))
    )
    op.create_table('course_collaborators',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_course_collaborators_added_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_collaborators_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_collaborators_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'user_id', name=op.f('pk_course_collaborators'))
    )
    op.create_table('course_modules',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_modules_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_modules')),
    sa.UniqueConstraint('course_id', 'position', name='uq_course_modules_position')
    )
    op.create_index(op.f('ix_course_modules_course_id'), 'course_modules', ['course_id'], unique=False)
    op.create_table('assessments',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('minimum_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_assessments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], name=op.f('fk_assessments_module_id_course_modules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_index('ix_assessments_course_id', 'assessments', ['course_id'], unique=False)
    op.create_index('ix_assessments_module_id', 'assessments', ['module_id'], unique=False)
    op.create_table('course_assignment_groups',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['course_assignments.id'], name=op.f('fk_course_assignment_groups_assignment_id_course_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_course_assignment_groups_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id', 'group_id', name=op.f('pk_course_assignment_groups'))
    )
    op.create_table('course_assignment_users',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['course_assignments.id'], name=op.f('fk_course_assignment_users_assignment_id_course_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_assignment_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id', 'user_id', name=op.f('pk_course_assignment_users'))
    )
    op.create_table('enrollments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('enrollment_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("enrollment_type IN ('ASSIGNMENT', 'MANUAL', 'RETAKE')", name=op.f('ck_enrollments_enrollment_type_valid')),
    sa.CheckConstraint("status IN ('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'PASSED', 'FAILED', 'OVERDUE', 'BLOCKED', 'CANCELLED')", name=op.f('ck_enrollments_status_valid')),
    sa.ForeignKeyConstraint(['assignment_id'], ['course_assignments.id'], name=op.f('fk_enrollments_assignment_id_course_assignments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_enrollments_course_id_courses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments'))
    )
    op.create_index('ix_enrollments_course_id', 'enrollments', ['course_id'], unique=False)
    op.create_index('ix_enrollments_due_date', 'enrollments', ['due_date'], unique=False)
    op.create_index('ix_enrollments_status', 'enrollments', ['status'], unique=False)
    op.create_index('ix_enrollments_user_id', 'enrollments', ['user_id'], unique=False)
    op.create_index('ix_enrollments_user_id_course_id', 'enrollments', ['user_id', 'course_id'], unique=False)
    op.create_table('lessons',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('completion_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("completion_type IN ('MANUAL', 'AUTO')", name=op.f('ck_lessons_completion_type_valid')),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], name=op.f('fk_lessons_module_id_course_modules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons')),
    sa.UniqueConstraint('module_id', 'position', name='uq_lessons_position')
    )
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('IN_PROGRESS', 'SUBMITTED', 'PASSED', 'FAILED')", name=op.f('ck_assessment_attempts_status_valid')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_attempts_assessment_id_assessments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_assessment_attempts_enrollment_id_enrollments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_attempts')),
    sa.UniqueConstraint('enrollment_id', 'assessment_id', 'attempt_number', name='uq_assessment_attempts_number')
    )
    op.create_index('ix_assessment_attempts_assessment_id', 'assessment_attempts', ['assessment_id'], unique=False)
    op.create_index('ix_assessment_attempts_enrollment_id', 'assessment_attempts', ['enrollment_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_questions_assessment_id_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_questions')),
    sa.UniqueConstraint('assessment_id', 'position', name='uq_assessment_questions_position')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.create_table('lesson_contents',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_type IN ('TEXT', 'VIDEO', 'PDF', 'IMAGE', 'AUDIO', 'YOUTUBE', 'VIMEO', 'LINK')", name=op.f('ck_lesson_contents_content_type_valid')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_contents_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_contents')),
    sa.UniqueConstraint('lesson_id', 'position', name='uq_lesson_contents_position')
    )
    op.create_index(op.f('ix_lesson_contents_lesson_id'), 'lesson_contents', ['lesson_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')", name=op.f('ck_lesson_progress_status_valid')),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name=op.f('ck_lesson_progress_progress_percentage_range')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_lesson_progress_enrollment_id_enrollments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_progress_lesson_id_lessons'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_progress')),
    sa.UniqueConstraint('enrollment_id', 'lesson_id', name='uq_lesson_progress_enrollment_lesson')
    )
    op.create_index('ix_lesson_progress_enrollment_id', 'lesson_progress', ['enrollment_id'], unique=False)
    op.create_index('ix_lesson_progress_lesson_id', 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index('ix_lesson_progress_status', 'lesson_progress', ['status'], unique=False)
    op.create_table('question_options',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], name=op.f('fk_question_options_question_id_assessment_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_options')),
    sa.UniqueConstraint('question_id', 'position', name='uq_question_options_position')
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('attempt_answers',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option_id', sa.UUID(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], name=op.f('fk_attempt_answers_attempt_id_assessment_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], name=op.f('fk_attempt_answers_question_id_assessment_questions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], name=op.f('fk_attempt_answers_selected_option_id_question_options'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_answers')),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_answers_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempt_answers')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index('ix_lesson_progress_status', table_name='lesson_progress')
    op.drop_index('ix_lesson_progress_lesson_id', table_name='lesson_progress')
    op.drop_index('ix_lesson_progress_enrollment_id', table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_lesson_contents_lesson_id'), table_name='lesson_contents')
    op.drop_table('lesson_contents')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index('ix_assessment_attempts_enrollment_id', table_name='assessment_attempts')
    op.drop_index('ix_assessment_attempts_assessment_id', table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index('ix_enrollments_user_id_course_id', table_name='enrollments')
    op.drop_index('ix_enrollments_user_id', table_name='enrollments')
    op.drop_index('ix_enrollments_status', table_name='enrollments')
    op.drop_index('ix_enrollments_due_date', table_name='enrollments')
    op.drop_index('ix_enrollments_course_id', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_table('course_assignment_users')
    op.drop_table('course_assignment_groups')
    op.drop_index('ix_assessments_module_id', table_name='assessments')
    op.drop_index('ix_assessments_course_id', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_course_modules_course_id'), table_name='course_modules')
    op.drop_table('course_modules')
    op.drop_table('course_collaborators')
    op.drop_table('course_categories')
    op.drop_index(op.f('ix_course_assignments_course_id'), table_name='course_assignments')
    op.drop_table('course_assignments')
    op.drop_table('user_groups')
    op.drop_index('ix_courses_status', table_name='courses')
    op.drop_index('ix_courses_published_at', table_name='courses')
    op.drop_index('ix_courses_owner_id', table_name='courses')
    op.drop_table('courses')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role_id', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('groups')
    op.drop_table('categories')
    # ### end Alembic commands ###
